apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: {{ .Values.apiGateway.image }}
          imagePullPolicy: Never
          ports:
            - containerPort: {{ .Values.apiGateway.port }}
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: jwt-secret
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.apiGateway.port }}
            initialDelaySeconds: 20
            periodSeconds: 10
