apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
        - name: eureka-server
          image: {{ .Values.eurekaServer.image }}
          imagePullPolicy: Never
          ports:
            - containerPort: {{ .Values.eurekaServer.port }}
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.eurekaServer.port }}
            initialDelaySeconds: 20
            periodSeconds: 10
