apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  selector:
    app: kafka
  ports:
    - name: broker
      port: {{ .Values.kafka.port }}
      targetPort: {{ .Values.kafka.port }}
    - name: host
      port: {{ .Values.kafka.hostPort }}
      targetPort: {{ .Values.kafka.hostPort }}
