apiVersion: v1
kind: Service
metadata:
  name: like-dislike-service
spec:
  selector:
    app: like-dislike-service
  ports:
    - port: {{ .Values.likeDislikeService.port }}
      targetPort: {{ .Values.likeDislikeService.port }}
