apiVersion: v1
kind: Service
metadata:
  name: tag-service
  namespace: blog
spec:
  selector:
    app: tag-service
  ports:
    - port: {{ .Values.tagService.port }}
      targetPort: {{ .Values.tagService.port }}
