apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: {{ .Values.userService.image }}
          imagePullPolicy: Never
          ports:
            - containerPort: {{ .Values.userService.port }}
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: jwt-secret
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_DB
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.userService.port }}
            initialDelaySeconds: 25
            periodSeconds: 10
