apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: blog
spec:
  selector:
    app: zookeeper
  ports:
    - port: {{ .Values.zookeeper.port }}
      targetPort: {{ .Values.zookeeper.port }}
