apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - secrets.yaml
  - configmap.yaml
  - infra/postgres.yaml
  - infra/zookeeper.yaml
  - infra/kafka.yaml
  - infra/redis.yaml
  - services/eureka-server.yaml
  - services/api-gateway.yaml
  - services/userservice.yaml
  - services/post-service.yaml
  - services/comment-service.yaml
  - services/like-dislike-service.yaml
  - services/tag-service.yaml
