apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: blog
type: Opaque
stringData:
  POSTGRES_USER: postgres # base64 encoded value of 'postgres'
  POSTGRES_PASSWORD: postgres  # base64 encoded value of 'password'
  POSTGRES_DB: main_db

---

apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: blog
type: Opaque
stringData:
  JWT_SECRET: change-this-to-a-real-32+char-secret
