spring:
  application:
    name: eureka-server
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration

server:
  port: ${PORT:8761}

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:${PORT:8761}/eureka/
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 60000

management:
  endpoints:
    web:
      exposure:
        include: "*"
